name: facebook/rocksdb/jobs-linux-other-checks
on: [push, pull_request]
jobs:
  build-linux-clang10-clang-analyze:
    runs-on:
      group: 2xlarge
    container:
      image: zjay437/rocksdb:0.6
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/pre-steps"
    - run: CC=clang-10 CXX=clang++-10 ROCKSDB_DISABLE_ALIGNED_NEW=1 CLANG_ANALYZER="/usr/bin/clang++-10" CLANG_SCAN_BUILD=scan-build-10 USE_CLANG=1 make V=1 -j32 analyze
    - uses: "./.github/actions/post-steps"
    - name: compress test report
      run: tar -cvzf scan_build_report.tar.gz scan_build_report
      if: failure()
    - uses: actions/upload-artifact@v3.1.3
      with:
        path: scan_build_report.tar.gz
  build-linux-unity-and-headers:
    runs-on:
      group: large
    container:
      image: gcc:latest
    env:
      EXTRA_CXXFLAGS: "-mno-avx512f"
    steps:
    - uses: actions/checkout@v4.1.0
    - run: apt-get update -y && apt-get install -y libgflags-dev
    - name: Unity build
      run: make V=1 -j8 unity_test
    - run: make V=1 -j8 -k check-headers
    - uses: "./.github/actions/post-steps"
  build-linux-mini-crashtest:
    runs-on:
      group: large
    container:
      image: zjay437/rocksdb:0.6
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/pre-steps"
    - run: ulimit -S -n `ulimit -H -n` && make V=1 -j8 CRASH_TEST_EXT_ARGS='--duration=960 --max_key=2500000 --use_io_uring=0' blackbox_crash_test_with_atomic_flush
    - uses: "./.github/actions/post-steps"
