name: facebook/rocksdb/nightly
on:
  schedule:
  - cron: 0 9 * * *
  workflow_dispatch:
jobs:
  build-format-compatible:
    runs-on:
      group: 2xlarge
    container:
      image: zjay437/rocksdb:0.6
      options: --shm-size=16gb
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/pre-steps"
    - name: test
      run: |-
        export TEST_TMPDIR=/dev/shm/rocksdb
        rm -rf /dev/shm/rocksdb
        mkdir /dev/shm/rocksdb
        git config --global --add safe.directory /__w/rocksdb/rocksdb
        tools/check_format_compatible.sh
    - uses: "./.github/actions/post-steps"
  build-linux-arm-test-full:
    runs-on:
      group: arm64large
    container:
      image: ubuntu-2004:202111-02
      options: --shm-size=16gb
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/pre-steps"
    - uses: "./.github/actions/install-gflags"
    - run: make V=1 J=4 -j4 check
    - uses: "./.github/actions/post-steps"
  build-linux-run-microbench:
    runs-on:
      group: 2xlarge
    container:
      image: zjay437/rocksdb:0.6
      options: --shm-size=16gb
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/pre-steps"
    - run: DEBUG_LEVEL=0 make -j32 run_microbench
    - uses: "./.github/actions/post-steps"
  build-linux-non-shm:
    runs-on:
      group: 2xlarge
    container:
      image: zjay437/rocksdb:0.6
      options: --shm-size=16gb
    env:
      TEST_TMPDIR: "/tmp/rocksdb_test_tmp"
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/pre-steps"
    - run: make V=1 -j32 check
    - uses: "./.github/actions/post-steps"
  build-linux-clang-13-asan-ubsan-with-folly:
    runs-on:
      group: 2xlarge
    container:
      image: zjay437/rocksdb:0.6
      options: --shm-size=16gb
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/pre-steps"
    - uses: "./.github/actions/setup-folly"
    - uses: "./.github/actions/build-folly"
    - run: CC=clang-13 CXX=clang++-13 LIB_MODE=static USE_CLANG=1 USE_FOLLY=1 COMPILE_WITH_UBSAN=1 COMPILE_WITH_ASAN=1 make -j32 check
    - uses: "./.github/actions/post-steps"
  build-linux-valgrind:
    runs-on:
      group: 2xlarge
    container:
      image: zjay437/rocksdb:0.6
      options: --shm-size=16gb
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/pre-steps"
    - run: PORTABLE=1 make V=1 -j32 valgrind_test
    - uses: "./.github/actions/post-steps"
