name: facebook/rocksdb/nightly
on: workflow_dispatch
jobs:
  # These jobs would be in nightly but are failing or otherwise broken for
  # some reason.
  build-linux-arm-test-full:
    if: ${{ github.repository_owner == 'facebook' }}
    runs-on:
      labels: arm64large
    container:
      image: ubuntu-2004:202111-02
      options: --shm-size=16gb
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/pre-steps"
    - uses: "./.github/actions/install-gflags"
    - run: make V=1 J=4 -j4 check
    - uses: "./.github/actions/post-steps"
