name: Check buck targets and code format
on: [push, pull_request]
jobs:
  check:
    name: Check TARGETS file and code format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout feature branch
      uses: actions/checkout@v2

    - name: Fetch from upstream
      run: |
        git remote add upstream https://github.com/facebook/rocksdb.git && git fetch upstream

    - name: Where am I
      run: |
        echo git status && git status

    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Install Dependencies
      run: python -m pip install --upgrade pip

    - name: Install argparse
      run: pip install argparse

    - name: Download clang-format-diff.py
      uses: wei/wget@v1
      with:
        args: https://raw.githubusercontent.com/llvm-mirror/clang/master/tools/clang-format/clang-format-diff.py

    - name: Compute merge base between PR and upstream/master
      id: merge_base
      run: |
        echo "::set-output name=MERGE_BASE::$(git merge-base upstream/master HEAD)"

    - name: Format diff
      id: format_diff
      run: |
        echo "::set-output name=FORMAT_DIFF_OUTPUT::$(git diff -U0 ${{steps.merge_base.outputs.MERGE_BASE}} | python clang-format-diff.py -p 1 | head -n 1)"

    - name: Check format
      run: |
        if [ -z "${{steps.format_diff.outputs.FORMAT_DIFF_OUTPUT}}" ]; then exit 0; else exit 1; fi

    - name: Compare buckify output
      run: make check-buck-targets
